Update ``py-geth`` version and re-generate integration test fixture with geth ``v1.11.2``.
